name: Action on Pull Request to generate Kong Config from Spec and Validate it

on:
  pull_request:
    branches:
      - main
      
jobs:
  deploy_to_kong:
    runs-on: self-hosted
    name: Generate Kong config from Spec and Validate config
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint OpenAPI Specification
        run: inso lint spec openapi/bankong-v1.3.0.yaml --ci -w .
      - name: Test OpenAPI Spec
        run: inso run test uts_97298 --env localdev --ci -w .
      - name: Create OpenAPI Specification From Insomnia
        run: inso export spec spc_ca6fc --output openapi/bankong-openapi.yaml --ci -w.
      - name: Generate Kong declarative configuration from Spec
        run: deck file openapi2kong --spec openapi/bankong-openapi.yaml --output-file bangkong-deck3.x.yaml
      - name: Validate Kong declarative configuration
        run: deck gateway validate bankong-deck3.x.yaml
