name: Action on Pull Request to generate Kong Config from Spec and Validate it

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_to_kong:
    runs-on: self-hosted
    name: Generate Kong config from Spec and Validate config
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint OpenAPI Specification
        run: inso lint spec spc_23d31c --ci
      - name: Test OpenAPI Spec
        run: inso run test uts_145cb5 --env localdev --ci
      - name: Generate Kong declarative configuration from Spec
        run: inso generate config ./openapi/bankong-v1.3.0.yaml --type declarative > kong2.x.yaml
      - name: Convert configuration for 3.0
        run: deck convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file kong2.x.yaml --output-file kong3.x.yaml
      - name: Validate Kong declarative configuration
        run: deck validate -s kong3.x.yaml
